### ISSUE TITLE
Error in dimnames(x) <- dn :    length of 'dimnames' [2] not equal to array extent

### ISSUE THREAD

**Issue by romanos-sp** [cancerdatasci/ceres#7] opened 2018-03-19 21:55 UTC
Hello, 

I am trying to run my own data and I bump into this error message when I prepare_ceres_inputs

_getting copy number data per locus...

Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent_

Any suggestions?

**Comment by romanos-sp** [comment] 2018-03-20 13:48
Hi again, 

It seems that the code breaks at intersect_guide_with_copy_number. The issue I think only appears if I run a single cell line and it has to do with selecting column CN from cn_seg_gr. I will redo with two cell lines and see if it runs smoothly. 

UPDATE: It runs smoothly with at least two cell lines. 

Thanks!

**Comment by funpys** [comment] 2018-03-23 08:13
Hi,
I've got same problem, and solved in same way, using additional dummy cell line.
However, it seems that the output is changing with same input data according to data of dummy cell line. 
Didn't you face this problem?

**Comment by romanos-sp** [comment] 2018-03-23 13:48
Hello, 

I understand that CERES shares information across cell lines, although I have yet to look through the code and find what kind of information is shared. But that pretty much explains your problem. 

I would not use a dummy column. If you only have the single cell line, perhaps you can add a cell line from CERES example data, as they are ready to run. That being said, until we figure out what part of the code shares information across cell lines, you cannot be confident that your results are reliable. 

I hope this helps.

**Comment by j-g-b** [comment] 2018-03-23 13:58
Thanks for your patience, guys. I'm working on pushing a patch that will take care of the single cell line case.

@prxrsp is right to say that the output will change because CERES tries use the dummy cell line as an informative partner. The sharing is done through an additive fixed effects term in the mixed effects model representing something like the "average gene effect across all cell lines", from which each individual cell line may differ. The model regularizes the cell-line-specific effects towards this mean effect, though, so if the values of your dummy cell line change, then so will those in your cell line of interest. I would not recommend adding fake cell line data for this reason.

The problem is definitely in prepare_inputs and probably has to do with a dimensionless array getting generated when a matrix is expected somewhere. I'll comment back when I've confirmed that a fix is ready.

**Comment by j-g-b** [comment] 2018-03-23 15:41
The latest commit seems to work with one cell line; let me know how it goes.

FYI we noticed that if you try to run prepare_inputs with a cell line that is not present in the dependency data .gct, one of these dimnames errors pops up, so double-check that all of the names match.

**Comment by funpys** [comment] 2018-03-26 05:32
Thanks for nice comments, I will let you know when I get the result.
I have one more question. 
When I run wrap_ceres, I used several replicates for each cell line as a input, then final output is only 1 column for 1 cell line. I searched codes in wrap_ceres, but final step (fit_ceres) seems quite complicated. Could  you tell me how replicates are merged to one column?

**Comment by funpys** [comment] 2018-03-26 07:37
Bellow is the error message from prepare_ceres_input with single cell line data.

getting copy number data per locus...

Error in set_rownames(., rownames(.) %>% str_extract("chr.+$")) : 
  attempt to set 'rownames' on an object with no dimensions

I think intersect_locus_with_cn_seg need to be revised for single cell line data.

**Comment by j-g-b** [comment] 2018-03-27 14:08
I think I fixed the problem, which was occurring because a 1-d matrix was being indexed at its rows, and R returns dimensionless vectors unless one specifies `one_d_mat[1:10, , drop=F]`

Hopefully that takes care of everything. Again, let us know if that doesn't solve the problem or creates further issues.

As for your previous comment, CERES is finding parameters to best fit the data for each guide i and cell line j. If there's only one replicate of that guide / cell line pair, then CERES will output one value for that one data point and evaluate the squared error. When multiple replicates are present, CERES still only outputs one value for guide i and cell line j, but now the mean squared error across the replicate data points is calculated.

**Comment by funpys** [comment] 2018-03-29 07:46
Thanks a lot!
Actually, I've got another error in same step.

getting copy number data per locus...

Error in x[!i, ] : incorrect number of dimensions

**Comment by j-g-b** [comment] 2018-05-18 13:45
Terribly sorry for taking so long to get around to this. I think I resolved the issue which had to do with matrix dimensions getting dropped in the case of a single cell line.

**Closed as completed** 2018-06-20 12:23 UTC
